filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log
    processors:
      - add_docker_metadata: ~

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml

output.logstash:
  enabled: true
  hosts: ["logstash:5044"]

setup.kibana:
  host: "kibana:5601"

logging.level: info
logging.to_files: false
